version: "3"
services:
  trainapp:
    build: ./trainapp
    depends_on:
      - spark
    environment:
      - "SPARK_MASTER=spark://spark:7077"
      - "SPARK_EXECUTOR_MEMORY=4g"
    command: >
      --lrmodel hdfs://192.168.1.180:9000/tmp/models/spark-logistic-regression-model
      --vcmodel hdfs://192.168.1.180:9000/tmp/models/spark-cv-model
      --jdbcurl jdbc:postgresql://192.168.1.180:5432/postgres
    restart: "no"